version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - zenchatbackend_data:/app

  client:
    build:
      context: ./client
    ports:
      - "3002:80"
    env_file:
      - ./client/.env
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongod
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ZenChat

volumes:
  mongo_data:
  zenchatbackend_data:
